version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    networks:
      - internal

  web:
    image: webdevops/php-apache-dev:8.1-alpine
    container_name: web
    restart: always
    user: application
    environment:
      - WEB_ALIAS_DOMAIN=magento-test.local
      - WEB_DOCUMENT_ROOT=/app/pub
      - PHP_DATE_TIMEZONE=EST
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=2048M
      - PHP_MAX_EXECUTION_TIME=300
      - PHP_POST_MAX_SIZE=500M
      - PHP_UPLOAD_MAX_FILESIZE=1024M
    volumes:
      - ./src:/app:cached
    ports:
      - "80:80"
      - "443:443"
      - "32823:22"
    networks:
      - internal
    depends_on:
      - db
      - elasticsearch
    links:
      - db
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - node.name=es-node-1
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - internal

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=magento
      - PMA_PASSWORD=magento
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - internal

volumes:
  dbdata:
    driver: local
  esdata:
    driver: local

networks:
  internal:
    driver: bridge
